# Generated by Django 4.2.10 on 2024-02-28 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USER_TG_ID', models.BigIntegerField(unique=True)),
                ('USER_LOGIN', models.CharField(max_length=200, unique=True)),
                ('USER_FULL_NAME', models.CharField(max_length=256)),
                ('USER_LEVEL', models.SmallIntegerField()),
                ('USER_ACCESS', models.SmallIntegerField()),
                ('CREATE_TIME', models.DateTimeField()),
                ('UPDATE_TIME', models.DateTimeField()),
            ],
            options={
                'db_table': 'USERS',
            },
        ),
    ]
