# Generated by Django 4.2.10 on 2024-02-29 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LEVEL_TEXT', models.CharField(max_length=200, unique=True)),
                ('CREATE_TIME', models.DateTimeField(auto_now_add=True)),
                ('UPDATE_TIME', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Доступ',
                'verbose_name_plural': 'Доступы',
                'db_table': 'Acces',
            },
        ),
        migrations.CreateModel(
            name='Constant',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('constant_name', models.CharField(db_column='constant_name', max_length=200)),
                ('constant_value', models.CharField(db_column='constant_value', max_length=200)),
                ('create_time', models.DateTimeField(db_column='create_time')),
                ('update_time', models.DateTimeField(db_column='update_time')),
            ],
            options={
                'db_table': 'constant',
            },
        ),
        migrations.CreateModel(
            name='Quize',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('quize_name', models.CharField(db_column='quize_name', max_length=200)),
                ('quize_description', models.CharField(db_column='quize_description', max_length=200)),
                ('create_time', models.DateTimeField(db_column='create_time')),
                ('update_time', models.DateTimeField(db_column='update_time')),
            ],
            options={
                'db_table': 'quize',
            },
        ),
        migrations.CreateModel(
            name='QuizeAnswer',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('question_number', models.IntegerField(db_column='question_number')),
                ('answer_number', models.IntegerField(db_column='answer_number')),
                ('answer_text', models.CharField(db_column='answer_text', max_length=200)),
                ('create_time', models.DateTimeField(db_column='create_time')),
                ('update_time', models.DateTimeField(db_column='update_time')),
                ('id_quize', models.OneToOneField(db_column='id_quize', on_delete=django.db.models.deletion.CASCADE, to='main.quize')),
            ],
            options={
                'db_table': 'quize_answer',
            },
        ),
        migrations.CreateModel(
            name='QuizeStatus',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('status_text', models.CharField(db_column='status_text', max_length=200)),
                ('create_time', models.DateTimeField(db_column='create_time')),
                ('update_time', models.DateTimeField(db_column='update_time')),
            ],
            options={
                'db_table': 'quize_qtatus',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('id_user_tg', models.BigIntegerField(db_column='id_user_tg', unique=True)),
                ('user_login', models.CharField(db_column='user_login', max_length=200)),
                ('user_full_name', models.CharField(db_column='user_full_name', max_length=200)),
                ('user_access', models.IntegerField(db_column='user_access')),
                ('create_time', models.DateTimeField(db_column='create_time')),
                ('update_time', models.DateTimeField(db_column='update_time')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='UserLevel',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('level_text', models.CharField(db_column='level_text', max_length=200)),
                ('min_level_score', models.IntegerField(db_column='min_level_score')),
                ('max_level_score', models.IntegerField(db_column='max_level_score')),
                ('create_time', models.DateTimeField(db_column='create_time')),
                ('update_time', models.DateTimeField(db_column='update_time')),
            ],
            options={
                'db_table': 'user_level',
            },
        ),
        migrations.CreateModel(
            name='UserQuize',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('question_number', models.IntegerField(db_column='question_number')),
                ('id_answer_last', models.IntegerField(db_column='id_answer_last')),
                ('quize_score', models.IntegerField(db_column='quize_score')),
                ('create_time', models.DateTimeField(db_column='create_time')),
                ('update_time', models.DateTimeField(db_column='update_time')),
                ('id_quize', models.OneToOneField(db_column='id_quize', on_delete=django.db.models.deletion.CASCADE, to='main.quize')),
                ('id_user_tg', models.OneToOneField(db_column='id_user_tg', on_delete=django.db.models.deletion.CASCADE, to='main.user', to_field='id_user_tg')),
                ('quize_status', models.OneToOneField(db_column='quize_status', on_delete=django.db.models.deletion.CASCADE, to='main.quizestatus')),
            ],
            options={
                'db_table': 'user_quize',
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('question_number', models.IntegerField(db_column='question_number')),
                ('create_time', models.DateTimeField(db_column='create_time')),
                ('update_time', models.DateTimeField(db_column='update_time')),
                ('id_answer', models.OneToOneField(db_column='id_answer', on_delete=django.db.models.deletion.CASCADE, to='main.quizeanswer')),
                ('id_user_quize', models.OneToOneField(db_column='id_user_quize', on_delete=django.db.models.deletion.CASCADE, to='main.userquize')),
                ('id_user_tg', models.OneToOneField(db_column='id_user_tg', on_delete=django.db.models.deletion.CASCADE, to='main.user', to_field='id_user_tg')),
            ],
            options={
                'db_table': 'user_answer',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='user_level',
            field=models.OneToOneField(db_column='user_level', on_delete=django.db.models.deletion.CASCADE, to='main.userlevel'),
        ),
        migrations.CreateModel(
            name='QuizeTrueAnswer',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('question_number', models.IntegerField(db_column='question_number')),
                ('create_time', models.DateTimeField(db_column='create_time')),
                ('update_time', models.DateTimeField(db_column='update_time')),
                ('id_answer', models.OneToOneField(db_column='id_answer', on_delete=django.db.models.deletion.CASCADE, to='main.quizeanswer')),
                ('id_quize', models.OneToOneField(db_column='id_quize', on_delete=django.db.models.deletion.CASCADE, to='main.quize')),
            ],
            options={
                'db_table': 'quize_true_answer',
            },
        ),
        migrations.CreateModel(
            name='QuizeQuestion',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('question_number', models.IntegerField(db_column='question_number')),
                ('question_text', models.CharField(db_column='question_text', max_length=200)),
                ('create_time', models.DateTimeField(db_column='create_time')),
                ('update_time', models.DateTimeField(db_column='update_time')),
                ('id_quize', models.OneToOneField(db_column='id_quize', on_delete=django.db.models.deletion.CASCADE, to='main.quize')),
            ],
            options={
                'db_table': 'quize_question',
            },
        ),
    ]
