# Generated by Django 4.2.10 on 2024-02-29 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LEVEL_TEXT', models.CharField(max_length=200, unique=True)),
                ('CREATE_TIME', models.DateTimeField(auto_now_add=True)),
                ('UPDATE_TIME', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Доступ',
                'verbose_name_plural': 'Доступы',
                'db_table': 'Acces',
            },
        ),
        migrations.AlterField(
            model_name='usertg',
            name='USER_LEVEL',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.level'),
        ),
        migrations.AlterField(
            model_name='usertg',
            name='USER_ACCESS',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.acces'),
        ),
    ]
