# Generated by Django 4.2.10 on 2024-03-01 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizeanswer',
            name='id_quize',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.quize', verbose_name='ID теста'),
        ),
        migrations.AlterField(
            model_name='quizequestion',
            name='id_quize',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.quize', verbose_name='ID теста'),
        ),
        migrations.AlterField(
            model_name='quizetrueanswer',
            name='id_answer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.quizeanswer', verbose_name='ID ответа'),
        ),
        migrations.AlterField(
            model_name='quizetrueanswer',
            name='id_quize',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.quize', verbose_name='ID теста'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_access',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.accesuser', verbose_name='Доступ пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.leveluser', verbose_name='Уровень пользователя'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='id_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.quizeanswer', verbose_name='ID ответа'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='id_user_quize',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.userquize', verbose_name='ID запушеного пользователем теста'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='id_user_tg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user', to_field='id_user_tg', verbose_name='ID пользователя в телеграм'),
        ),
        migrations.AlterField(
            model_name='userquize',
            name='id_quize',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.quize', verbose_name='ID теста'),
        ),
        migrations.AlterField(
            model_name='userquize',
            name='id_user_tg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user', to_field='id_user_tg', verbose_name='ID пользователя в телеграмм'),
        ),
        migrations.AlterField(
            model_name='userquize',
            name='quize_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.statusquize', verbose_name='ID статуса теста'),
        ),
    ]
