# Generated by Django 4.2.10 on 2024-03-01 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acces',
            old_name='CREATE_TIME',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='acces',
            old_name='UPDATE_TIME',
            new_name='update_time',
        ),
        migrations.RemoveField(
            model_name='acces',
            name='LEVEL_TEXT',
        ),
        migrations.AlterField(
            model_name='constant',
            name='constant_name',
            field=models.CharField(blank=True, db_column='constant_name', max_length=200),
        ),
        migrations.AlterField(
            model_name='constant',
            name='constant_value',
            field=models.CharField(blank=True, db_column='constant_value', max_length=200),
        ),
        migrations.AlterField(
            model_name='constant',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, db_column='create_time'),
        ),
        migrations.AlterField(
            model_name='constant',
            name='update_time',
            field=models.DateTimeField(auto_now=True, db_column='update_time'),
        ),
        migrations.AlterField(
            model_name='quize',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, db_column='create_time'),
        ),
        migrations.AlterField(
            model_name='quize',
            name='quize_description',
            field=models.CharField(blank=True, db_column='quize_description', max_length=200),
        ),
        migrations.AlterField(
            model_name='quize',
            name='quize_name',
            field=models.CharField(blank=True, db_column='quize_name', max_length=200),
        ),
        migrations.AlterField(
            model_name='quize',
            name='update_time',
            field=models.DateTimeField(auto_now=True, db_column='update_time'),
        ),
        migrations.AlterField(
            model_name='quizeanswer',
            name='answer_number',
            field=models.IntegerField(blank=True, db_column='answer_number'),
        ),
        migrations.AlterField(
            model_name='quizeanswer',
            name='answer_text',
            field=models.CharField(blank=True, db_column='answer_text', max_length=200),
        ),
        migrations.AlterField(
            model_name='quizeanswer',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, db_column='create_time'),
        ),
        migrations.AlterField(
            model_name='quizeanswer',
            name='id_quize',
            field=models.OneToOneField(blank=True, db_column='id_quize', on_delete=django.db.models.deletion.CASCADE, to='main.quize'),
        ),
        migrations.AlterField(
            model_name='quizeanswer',
            name='question_number',
            field=models.IntegerField(blank=True, db_column='question_number'),
        ),
        migrations.AlterField(
            model_name='quizeanswer',
            name='update_time',
            field=models.DateTimeField(auto_now=True, db_column='update_time'),
        ),
        migrations.AlterField(
            model_name='quizequestion',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, db_column='create_time'),
        ),
        migrations.AlterField(
            model_name='quizequestion',
            name='id_quize',
            field=models.OneToOneField(blank=True, db_column='id_quize', on_delete=django.db.models.deletion.CASCADE, to='main.quize'),
        ),
        migrations.AlterField(
            model_name='quizequestion',
            name='question_number',
            field=models.IntegerField(blank=True, db_column='question_number'),
        ),
        migrations.AlterField(
            model_name='quizequestion',
            name='question_text',
            field=models.CharField(blank=True, db_column='question_text', max_length=200),
        ),
        migrations.AlterField(
            model_name='quizequestion',
            name='update_time',
            field=models.DateTimeField(auto_now=True, db_column='update_time'),
        ),
        migrations.AlterField(
            model_name='quizestatus',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, db_column='create_time'),
        ),
        migrations.AlterField(
            model_name='quizestatus',
            name='status_text',
            field=models.CharField(blank=True, db_column='status_text', max_length=200),
        ),
        migrations.AlterField(
            model_name='quizestatus',
            name='update_time',
            field=models.DateTimeField(auto_now=True, db_column='update_time'),
        ),
        migrations.AlterField(
            model_name='quizetrueanswer',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, db_column='create_time'),
        ),
        migrations.AlterField(
            model_name='quizetrueanswer',
            name='id_answer',
            field=models.OneToOneField(blank=True, db_column='id_answer', on_delete=django.db.models.deletion.CASCADE, to='main.quizeanswer'),
        ),
        migrations.AlterField(
            model_name='quizetrueanswer',
            name='id_quize',
            field=models.OneToOneField(blank=True, db_column='id_quize', on_delete=django.db.models.deletion.CASCADE, to='main.quize'),
        ),
        migrations.AlterField(
            model_name='quizetrueanswer',
            name='question_number',
            field=models.IntegerField(blank=True, db_column='question_number'),
        ),
        migrations.AlterField(
            model_name='quizetrueanswer',
            name='update_time',
            field=models.DateTimeField(auto_now=True, db_column='update_time'),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, db_column='create_time'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_user_tg',
            field=models.BigIntegerField(blank=True, db_column='id_user_tg', unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='update_time',
            field=models.DateTimeField(auto_now=True, db_column='update_time'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_full_name',
            field=models.CharField(blank=True, db_column='user_full_name', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_login',
            field=models.CharField(blank=True, db_column='user_login', max_length=200),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, db_column='create_time'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='question_number',
            field=models.IntegerField(blank=True, db_column='question_number'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='update_time',
            field=models.DateTimeField(auto_now=True, db_column='update_time'),
        ),
        migrations.AlterField(
            model_name='userlevel',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, db_column='create_time'),
        ),
        migrations.AlterField(
            model_name='userlevel',
            name='level_text',
            field=models.CharField(blank=True, db_column='level_text', max_length=200),
        ),
        migrations.AlterField(
            model_name='userlevel',
            name='max_level_score',
            field=models.IntegerField(blank=True, db_column='max_level_score'),
        ),
        migrations.AlterField(
            model_name='userlevel',
            name='min_level_score',
            field=models.IntegerField(blank=True, db_column='min_level_score'),
        ),
        migrations.AlterField(
            model_name='userlevel',
            name='update_time',
            field=models.DateTimeField(auto_now=True, db_column='update_time'),
        ),
        migrations.AlterField(
            model_name='userquize',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, db_column='create_time'),
        ),
        migrations.AlterField(
            model_name='userquize',
            name='id_answer_last',
            field=models.IntegerField(blank=True, db_column='id_answer_last'),
        ),
        migrations.AlterField(
            model_name='userquize',
            name='question_number',
            field=models.IntegerField(blank=True, db_column='question_number'),
        ),
        migrations.AlterField(
            model_name='userquize',
            name='update_time',
            field=models.DateTimeField(auto_now=True, db_column='update_time'),
        ),
        migrations.AddField(
            model_name='acces',
            name='level_text',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
    ]
