# Generated by Django 4.2.10 on 2024-03-01 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_quizeanswer_id_quize_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizetrueanswer',
            options={'verbose_name': 'Правильный ответ для теста', 'verbose_name_plural': 'Правильные ответы для теста'},
        ),
    ]
