# Generated by Django 4.2.10 on 2024-03-01 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_constant_constant_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='constant',
            options={'verbose_name': 'Константа', 'verbose_name_plural': 'Константы'},
        ),
        migrations.AlterModelOptions(
            name='quize',
            options={'verbose_name': 'Тест', 'verbose_name_plural': 'Тесты'},
        ),
        migrations.AlterModelOptions(
            name='quizeanswer',
            options={'verbose_name': 'Ответ теста', 'verbose_name_plural': 'Ответы теста'},
        ),
        migrations.AlterModelOptions(
            name='quizequestion',
            options={'verbose_name': 'Вопрос теста', 'verbose_name_plural': 'Вопросы теста'},
        ),
        migrations.AlterModelOptions(
            name='quizestatus',
            options={'verbose_name': 'Статус теста', 'verbose_name_plural': 'Статусы теста'},
        ),
        migrations.AlterModelOptions(
            name='quizetrueanswer',
            options={'verbose_name': 'Правильный вопрос для теста', 'verbose_name_plural': 'Правильные вопросы для теста'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь в telegramm', 'verbose_name_plural': 'Пользователи в telegramm'},
        ),
        migrations.AlterModelOptions(
            name='useranswer',
            options={'verbose_name': 'Ответ пользователя', 'verbose_name_plural': 'Ответы пользователя'},
        ),
        migrations.AlterModelOptions(
            name='userlevel',
            options={'verbose_name': 'Уровень пользователя', 'verbose_name_plural': 'Уровни пользователя'},
        ),
        migrations.AlterModelOptions(
            name='userquize',
            options={'verbose_name': 'Запущенный тест пользователя', 'verbose_name_plural': 'Запущенные тесты пользователя'},
        ),
        migrations.AlterField(
            model_name='constant',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='quize',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='quizeanswer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='quizequestion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='quizestatus',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='quizetrueanswer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userlevel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userquize',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
