# Generated by Django 4.2.10 on 2024-03-01 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_user_options_alter_accesuser_create_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constant',
            name='constant_name',
            field=models.CharField(blank=True, max_length=200, unique=True, verbose_name='Наименование переменной'),
        ),
        migrations.AlterField(
            model_name='leveluser',
            name='level_text',
            field=models.CharField(blank=True, max_length=200, unique=True, verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='leveluser',
            name='max_level_score',
            field=models.IntegerField(blank=True, unique=True, verbose_name='Максимальный процент уровня'),
        ),
        migrations.AlterField(
            model_name='leveluser',
            name='min_level_score',
            field=models.IntegerField(blank=True, unique=True, verbose_name='Минималтный процент уровня'),
        ),
        migrations.AlterField(
            model_name='quize',
            name='quize_name',
            field=models.CharField(blank=True, max_length=200, unique=True, verbose_name='Имя теста'),
        ),
        migrations.AlterField(
            model_name='statusquize',
            name='status_text',
            field=models.CharField(blank=True, max_length=200, unique=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_login',
            field=models.CharField(blank=True, max_length=200, unique=True, verbose_name='Лонин пользователя в телеграмм'),
        ),
    ]
